// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // De CLI (migraties, generate) heeft de directe (niet-pooled) verbinding nodig.
    // De app zelf gebruikt DATABASE_URL (pooled) rechtstreeks in src/lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
